Port over hopsuit
Simple-Station/Parkstation-Friendly-Chainsaw pull request #22
Opened 2023-11-05 22:55 UTC by Finket

# Description

Port over https://github.com/Simple-Station/Parkstation/pull/87

- [x] HoP Hardsuit https://github.com/Simple-Station/Parkstation-Friendly-Chainsaw/issues/2

Note there are other changes in the original Hopsuit PR that I'll just list as tasks here just in case. I did not make those changes.

---

# Tasks

- [ ] command encryption key box
- [ ] command key box in HoP locker
- [ ] command remote in HoP locker

---

<details><summary><h1>Media</h1></summary>
<p>

![image](https://github.com/Simple-Station/Parkstation-Friendly-Chainsaw/assets/42383212/3c227250-ac6f-49c0-a2df-a9585a877556)

</p>
</details>

2023-11-05 23:29 UTC, DEATHB4DEFEAT requested changes

2023-11-05 23:29 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +      - id: ClothingOuterHardsuitHoP
```suggestion
      - id: ClothingOuterHardsuitHoP # Parkstation-HoPSuit
```

2023-11-05 23:29 UTC, DEATHB4DEFEAT commented on Resources/Textures/SimpleStation14/Clothing/Head/Hardsuits/hopsuit.rsi/meta.json
> +    "copyright": "Made by Cabbage#9633",
```suggestion
    "copyright": "Made by DSC@Cabbage#9633",
```

2023-11-05 23:29 UTC, DEATHB4DEFEAT commented on Resources/Textures/SimpleStation14/Clothing/OuterClothing/Hardsuits/hopsuit.rsi/meta.json
> +    "copyright": "Made by Cabbage#9633",
```suggestion
    "copyright": "Made by DSC@Cabbage#9633",
```

2023-11-06 06:04 UTC, Finket commented
Requested changes committed.

2023-11-06 07:02 UTC, DEATHB4DEFEAT approved these changes

2023-11-06 07:03 UTC, merged