Port cryosleep pod from CosmaticDrift
Simple-Station/Parkstation-Friendly-Chainsaw pull request #31
Opened 2024-01-16 14:02 UTC by Finket

# Description

As discussed in https://github.com/Simple-Station/Parkstation-Friendly-Chainsaw/pull/29.
Porting over from CosmaticDrift as in https://github.com/cosmatic-drift-14/cosmatic-drift/pull/49.

---

# Tasks

- [ ] Fix Sandbox Violations
- [ ] Guidebook entries

---

# Changelog

:cl:
- add: Cryosleep pod
- add: Lost and Found locker

2024-01-18 08:16 UTC, DEATHB4DEFEAT commented
I need to see how https://github.com/space-wizards/space-station-14/pull/24096 works, but we're probably keeping this one.

Also, should I close #29?

2024-01-18 08:32 UTC, DEATHB4DEFEAT requested changes

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Audio/SimpleStation14/Effects/attributions.yml
> +  source: "https://github.com/Finket/"
```suggestion
  source: "https://github.com/Finket/"

```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Content.Client/CosmaticDrift/CryoSleep/AcceptCryoWindow.cs
> +        });
Unholy amount of nesting, this should be flattened.

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Content.Server/CosmaticDrift/CryoSleep/CryoSleepSystem.cs
> +
```suggestion


```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Content.Server/CosmaticDrift/CryoSleep/CryoSleepSystem.cs
> +
```suggestion


```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Content.Server/CosmaticDrift/CryoSleep/CryoSleepSystem.cs
> +        SubscribeLocalEvent<CryoSleepComponent, GetVerbsEvent<AlternativeVerb>>(AddAlternativeVerbs);
```suggestion
        SubscribeLocalEvent<CryoSleepComponent, ComponentInit>(ComponentInit);

        SubscribeLocalEvent<CryoSleepComponent, GetVerbsEvent<AlternativeVerb>>(AddAlternativeVerbs);
```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Content.Server/CosmaticDrift/CryoSleep/CryoSleepSystem.cs
> +    public void CryoStoreBody(EntityUid mindId)
```suggestion

    public void CryoStoreBody(EntityUid mindId)
```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Audio/SimpleStation14/Effects/cryosleepopen.ogg
Name this `cryosleep_open.ogg`

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/cosmaticdrift/cryosleep/cryosleep-component.ftl
> +cryo-leave-announcement = {$character} ({$job}) is entering cryosleep.
```suggestion
cryo-leave-announcement = {$character} ({$job}) has gone into cryosleep.
```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/cosmaticdrift/cryosleep/cryosleep-component.ftl
> +accept-cryo-window-prompt-text-part = Enter cryo sleep and finish your shift as this character?
```suggestion
accept-cryo-window-prompt-text-part = Enter cryosleep and end your shift as this character?
```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/cosmaticdrift/cryosleep/cryosleep-component.ftl
> +accept-cryo-window-title = Cryo Sleep Chamber
```suggestion
accept-cryo-window-title = Cryostasis Sleep Chamber
```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/CosmaticDrift/Entities/Structures/Machines/cryo_sleep_pod.yml
> +        damage: 0
```suggestion
        damage: 0

```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/CosmaticDrift/Entities/Structures/Machines/cryo_sleep_pod.yml
> +  description: Perfect for a 10,000 year nap.
```suggestion
  description: Perfect for having a 10,000 year nap!
```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/CosmaticDrift/Entities/Structures/Machines/cryo_sleep_pod.yml
> +  name: cryo sleep chamber
```suggestion
  name: cryosleep chamber
```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/CosmaticDrift/Entities/Structures/Machines/cryo_sleep_pod.yml
Indent the components by a tab

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/CosmaticDrift/Entities/Structures/Storage/lockers.yml
> +    access: [["HeadOfPersonnel"]]
```suggestion
  components:
    - type: LostAndFound
    - type: EntityStorage
      capacity: 999 # Supposed to fit a lot.
    - type: Appearance
    - type: EntityStorageVisuals
      stateBaseClosed: lostandfound
      stateDoorOpen: lostandfound_open
      stateDoorClosed: lostandfound_door
    - type: AccessReader
      access: [["HeadOfPersonnel"]]
```

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Textures/CosmaticDrift/Structures/cryosleeppod.rsi/closed.png
Use the [green sleeper](https://github.com/EmoGarbage404/space-station-14/tree/9f3c7ad427a2800a352411941d672b0a1a03dbb9/Resources/Textures/Structures/cryostorage.rsi) sprite

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Textures/CosmaticDrift/Structures/cryosleeppod.rsi/meta.json
Can't comment on folders; name the RSI `cryosleep_pod.rsi`

2024-01-18 08:32 UTC, DEATHB4DEFEAT commented on Resources/Textures/Structures/Storage/closet.rsi/lostandfound.png
I don't want to comment on all three of these, name them `lost_and_found` instead of `lostandfound`

2024-01-19 22:33 UTC, DEATHB4DEFEAT requested changes

2024-01-19 22:33 UTC, DEATHB4DEFEAT commented on Content.Client/CosmaticDrift/CryoSleep/AcceptCryoWindow.cs
> +public sealed class AcceptCryoWindow : DefaultWindow
Try using a FancyWindow

2024-01-19 22:33 UTC, DEATHB4DEFEAT commented on Content.Client/CosmaticDrift/CryoSleep/AcceptCryoWindow.cs
> +            Children = {(new Label() {Text = Loc.GetString("accept-cryo-window-prompt-text-part")}), ButtonBox}
```suggestion
            Children = { (new Label() { Text = Loc.GetString("accept-cryo-window-prompt-text-part") }), ButtonBox }
```

2024-01-19 22:33 UTC, DEATHB4DEFEAT commented on Content.Client/CosmaticDrift/CryoSleep/AcceptCryoWindow.cs
Use XAMLUI to make this

2024-01-19 22:33 UTC, DEATHB4DEFEAT commented on Resources/Textures/Structures/Storage/closet.rsi/meta.json
..why is every locker in one RSI?
Move the lost and found into a new RSI in the CosmaticDrift namespace if possible

2024-01-19 22:33 UTC, DEATHB4DEFEAT commented on Resources/Textures/Structures/cryosleep_pod.rsi/meta.json
> +}
```suggestion
}

```

2024-01-19 22:33 UTC, DEATHB4DEFEAT commented on Resources/Textures/Structures/cryosleep_pod.rsi/meta.json
> +        ]
```suggestion
        [ 0.2, 0.2, 0.2, 0.2 ],
        [ 0.2, 0.2, 0.2, 0.2 ],
        [ 0.2, 0.2, 0.2, 0.2 ],
        [ 0.2, 0.2, 0.2, 0.2 ]
```

2024-01-19 22:33 UTC, DEATHB4DEFEAT commented on Resources/Textures/Structures/cryosleep_pod.rsi/meta.json
Move this RSI to the CosmaticDrift namespace

2024-01-19 22:33 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/CosmaticDrift/Entities/Structures/Machines/cryo_sleep_pod.yml
> +      delay: 999999
I think people should be able to move these, if anyone hides them or something an admin can make some more

2024-01-19 22:36 UTC, DEATHB4DEFEAT commented on Content.Server/CosmaticDrift/CryoSleep/CryoSleepComponent.cs
> +    public bool DoSpawns = false;
Does this do anything? This sounds really cool, should probably be a cvar.

2024-02-02 00:31 UTC, Finket commented
> I need to see how [space-wizards/space-station-14#24096](https://github.com/space-wizards/space-station-14/pull/24096) works, but we're probably keeping this one.
> 
> Also, should I close #29?

So, the PR above is merged, and basically have the same functionality. I could modify the cryogenic sleep units to use my sound effects etc. instead of this current PR...

2024-02-02 00:35 UTC, DEATHB4DEFEAT commented
> > I need to see how [space-wizards/space-station-14#24096](https://github.com/space-wizards/space-station-14/pull/24096) works, but we're probably keeping this one.
> > Also, should I close #29?
> 
> So, the PR above is merged, and basically have the same functionality. I could modify the cryogenic sleep units to use my sound effects etc. instead of this current PR...

I like the lost and found and I want to keep the sprites and sound from this PR

2024-02-02 00:37 UTC, Finket commented
> > > I need to see how [space-wizards/space-station-14#24096](https://github.com/space-wizards/space-station-14/pull/24096) works, but we're probably keeping this one.
> > > Also, should I close #29?
> > 
> > 
> > So, the PR above is merged, and basically have the same functionality. I could modify the cryogenic sleep units to use my sound effects etc. instead of this current PR...
> 
> I like the lost and found and I want to keep the sprites and sound from this PR

I believe the pod sprite is the same as the Wizden one. Also the way lost items is stored there is quite sleek--have you looked at it?
Regardless, lost and found has the advantage of items automatically going somewhere secure.

Let me know, and I'll take a look later at whether I should modify the Wizden code instead in this PR or remove it and use the CosmaticDrift code.

2024-02-02 00:50 UTC, DEATHB4DEFEAT commented
> > > > I need to see how [space-wizards/space-station-14#24096](https://github.com/space-wizards/space-station-14/pull/24096) works, but we're probably keeping this one.
> > > > Also, should I close #29?
> > > 
> > > 
> > > So, the PR above is merged, and basically have the same functionality. I could modify the cryogenic sleep units to use my sound effects etc. instead of this current PR...
> > 
> > 
> > I like the lost and found and I want to keep the sprites and sound from this PR
> 
> I believe the pod sprite is the same as the Wizden one. Also the way lost items is stored there is quite sleek--have you looked at it? Regardless, lost and found has the advantage of items automatically going somewhere secure.
> 
> Let me know, and I'll take a look later at whether I should modify the Wizden code instead in this PR or remove it and use the CosmaticDrift code.

The pod is the same, I forgot since everyone else has been using weird sprites.
The way lost items are stored is very nice but it seems they're stored on the pod itself, that doesn't sound very secure or reusable and we might do something like CD having cryo at arrivals so you don't want to go back and forth to get something.

2024-02-21 12:47 UTC, Finket commented
Discussed changes are complete

2024-02-24 13:52 UTC, Finket commented
Now, if there is no lost and found, going into cryo drops your items on the ground at the cryosleep pod. This PR is pretty much ready.

2024-02-25 21:35 UTC, DEATHB4DEFEAT requested changes

2024-02-25 21:35 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
None of this is commented and I don't like the mass moving of parts of this system

2024-02-25 21:35 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +        _audio.PlayPvs("/Audio/SimpleStation14/Effects/cryostasis.ogg", cryostorageEnt.Value, AudioParams.Default.WithVolume(6f));
The remove sound and its' audioparams should be a variable

2024-02-25 21:35 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
Either modify wizden's systems or make a whole new one and replace usages of theirs

2024-02-26 05:00 UTC, Finket commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
Very well, if I understood correctly: I will move the Lost and Found system stuff (UI) back into wizden's system: CryostorageSystem.cs. I will just make the UI check for the new Lost and Found component instead. This way the new functionality is all handled by one system.

2024-02-26 05:01 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
Sure

2024-02-26 05:36 UTC, Finket commented
Tested and working, cleaned into a modification of the original system. Note that wizden's component stuff is still moved to a new LostAndFoundComponent. I think this is necessary.

2024-02-26 08:30 UTC, Finket commented
Are the lost and found components and resources fine in the same namespace as cryosleep btw, or should I move them to a SimpleStation14 namespace?

2024-03-28 04:39 UTC, DEATHB4DEFEAT requested changes

2024-03-28 04:39 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +        private void OnBeforeUIOpened(Entity<LostAndFoundComponent> ent, ref BeforeActivatableUIOpenEvent args)
```suggestion
    private void OnBeforeUIOpened(Entity<LostAndFoundComponent> ent, ref BeforeActivatableUIOpenEvent args)
```

2024-03-28 04:39 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +
```suggestion
```

2024-03-28 04:39 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +        // try to get the lost and found and add the player to it
```suggestion
        // Try to get the lost and found and add the player to it
```

2024-03-28 04:39 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +        else // if there is no lost and found, just drop the items instead of deleting them
```suggestion
        else // If there is no lost and found, just drop the items instead of deleting them
```

2024-03-28 04:39 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +        // try to get the lost and found and remove the player from it
```suggestion
        // Try to get the lost and found and remove the player from it
```

2024-03-28 04:39 UTC, DEATHB4DEFEAT commented on Content.Shared/Bed/Cryostorage/SharedCryostorageSystem.cs
> +        // play sound, checking for client-side prediction to avoid double audio
```suggestion
        // Play sound, checking for client-side prediction to avoid double audio
```

2024-03-28 04:39 UTC, DEATHB4DEFEAT commented on Content.Shared/Bed/Cryostorage/SharedCryostorageSystem.cs
> +        // try to get the lost and found and remove the player from it
```suggestion
        // Try to get the lost and found and remove the player from it
```

2024-03-28 04:39 UTC, DEATHB4DEFEAT commented on Resources/Textures/Structures/Storage/lost_and_found.rsi/meta.json
> +      ]
```suggestion
      "delays": [ [ 1.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.5 ] ]
```

2024-04-29 04:59 UTC, DEATHB4DEFEAT requested changes

2024-04-29 04:59 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +        if (TryComp<LostAndFoundComponent>(storage, out var lostAndFoundComp))
You already got the lost and found comp, don't need to check again

2024-04-29 04:59 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +        query.MoveNext(out var storage, out var lostAndFoundComponent);
This should randomly pick one if multiple exist

2024-04-29 04:59 UTC, DEATHB4DEFEAT commented on Content.Server/Bed/Cryostorage/CryostorageSystem.cs
> +        }
I don't think this would work right with multiple storages

2024-04-29 04:59 UTC, DEATHB4DEFEAT commented on Content.Shared/Bed/Cryostorage/SharedCryostorageSystem.cs
> +        CompOrNull<LostAndFoundComponent>(storage)?.StoredPlayers.Remove(ent);
I don't think this would work with multiple storages either, find which storage the entity is in and remove itself.

2024-12-10 01:19 UTC, closed without merging