Hanbok
Simple-Station/Parkstation-Friendly-Chainsaw pull request #52
Opened 2024-02-14 20:26 UTC by toasterpm87

This reverts commit 6449fe9f20e18ea7eb3c10891e29e123d084b692.

# Description

Description.

---

# TODO

- [ ] Task
- [x] Completed Task

---

<details><summary><h1>Media</h1></summary>
<p>

</p>
</details>

---

# Changelog

:cl:
- add: Added fun!
- tweak: Tweaked fun!
- fix: Fixed fun!
- remove: Removed fun!

2024-02-14 20:28 UTC, toasterpm87 commented
![Hanbok](https://github.com/Simple-Station/Parkstation-Friendly-Chainsaw/assets/121322002/20114c81-bcd4-4687-940e-1ca1c6d876bf)

2024-02-21 21:34 UTC, DEATHB4DEFEAT approved these changes
lgtm, need to see what psp thinks about the Caldera folder

2024-02-21 21:35 UTC, toasterpm87 commented
> lgtm, need to see what psp thinks about the Caldera namespace

What's igtm?

2024-02-21 22:22 UTC, DEATHB4DEFEAT commented
> > lgtm, need to see what psp thinks about the Caldera namespace
> 
> What's igtm?

Looks
Good
To
Me

2024-02-22 20:11 UTC, Pspritechologist requested changes
Caldera namespace is probably fine? Assuming it's actually in the repo, it makes updating it from the source easier. 
Bit odd to have just the one entity, but

2024-02-22 20:11 UTC, Pspritechologist commented on Resources/Textures/Caldera/Clothing/Hanbok.rsi/icon.png
This should be the outfit folded up, not just the front-facing sprite.

2024-02-22 20:11 UTC, Pspritechologist commented on Resources/Prototypes/Caldera/Clothing/Outfits
> +  description: A traditional Korean dress
This item seems to not have a name?

2024-02-22 20:11 UTC, Pspritechologist commented on Resources/Textures/Caldera/Clothing/Hanbok.rsi/Equipped-INNERCLOTHING.png
The RSI directory name should not have any capitals in it.

2024-02-22 20:11 UTC, Pspritechologist commented on Resources/Textures/Caldera/Clothing/Hanbok.rsi/meta.json
> +    "copyright": "Plyush/katayusha",
This should make clear that you can be contacted on Discord under this name.

2024-02-22 20:12 UTC, toasterpm87 commented
> Caldera namespace is probably fine? Assuming it's actually in the repo, it makes updating it from the source easier. 
> Bit odd to have just the one entity, but

I will move more things into there.

2024-02-24 19:42 UTC, DEATHB4DEFEAT commented on Resources/Textures/Caldera/Clothing/Hanbok.rsi/icon.png
It should but I don't think any others do that

2024-02-25 22:35 UTC, toasterpm87 commented
i resolved all thingys

2024-03-06 05:24 UTC, DEATHB4DEFEAT commented
> i resolved all thingys

You don't seem to have pushed changes

2024-03-10 04:56 UTC, Pspritechologist commented on Resources/Textures/Caldera/Clothing/Hanbok.rsi/icon.png
Lots do

2024-03-10 04:57 UTC, Pspritechologist commented
You've marked everything as resolved, but have not actually updated anything in this pr.

2024-03-10 05:39 UTC, toasterpm87 commented
> You've marked everything as resolved, but have not actually updated anything in this pr.

Lmao I think I forgot to pr

2024-03-16 23:10 UTC, toasterpm87 commented
im gonna rewrite this

2024-03-16 23:10 UTC, closed without merging